name: release

on:
  push:

jobs:
  build:
    name: build-windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive
          
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: NuGet Restore
      run: |
        nuget restore RoundedTB.sln
      
    - name: Build
      run: |
        msbuild "-property:Configuration=Release" -t:RoundedTB
    - name: Get short commit hash
      id: shorthash
      run: |
        echo "short_hash=$(git rev-parse --short ${{ github.sha }})" >> $env:GITHUB_ENV
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rtb-artifacts-${{ env.short_hash }}
        path: |
          ${{ github.workspace }}\RoundedTB\bin\Release\*