name: release

on:
  push:

jobs:
  build:
    name: build-windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive
          
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: NuGet Restore
      run: |
        cd ${{ github.workspace }}
        nuget restore RoundedTB.sln
      
    - name: Build
      run: |
        cd ${{ github.workspace }}
        msbuild "-property:Configuration=Release" -t:RoundedTB

    - name: Pack output
      run: |
        cd ${{ github.workspace }}
        cd RoundedTB\bin\Release
        7z a ..\..\..\build.zip .\*
        cd ${{ github.workspace }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          .\build.zip
          
